// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../closurestrap/alert.js', ['closurestrap.alert'], ['goog.dom'], false);
goog.addDependency('../../../closurestrap/all.js', ['closurestrap.all'], ['closurestrap.alert'], false);
